---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# sarah.biza.m1ecap

Le premier commit de ce répertoire a été effectué le 16/04/2026 à 09h16.

Ce package a été développé dans le cadre de l’évaluation M1 ECAP du 16 avril.  
Il contient un jeu de données Spotify Wrapped 2025 ainsi que plusieurs fonctions d’analyse.

## Installation

Vous pouvez installer la version de développement depuis GitHub :

```{r}
# install.packages("pak")
pak::pak("sarahbiza82/sarah.biza.m1ecap")
```

## Exemple
```{r}
head(spotify_wrapped_2025)
```

```{r}
streams_by_genre(spotify_wrapped_2025)
```

```{r}
plot_streams_by_genre(spotify_wrapped_2025)
```

```{r}
filter_genre(spotify_wrapped_2025, "Pop")
```

```{r}
filter_country_streams(spotify_wrapped_2025, "USA", min_streams = 1)
```

## Réponse à l’exercice Git

```bash
git checkout master
git commit -m "commit A"
git checkout -b feature
git commit -m "commit B"
git checkout master
git commit -m "commit C"
git merge feature
```



